---
- name: Configure CA server
  hosts: ca-server
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../defaults/main/ca.yml"
    - "{{ playbook_dir }}/../../vars/main/ca.yml"
  tasks:
    - import_tasks: "{{ playbook_dir }}/provision.yml"
    - import_tasks: "{{ playbook_dir }}/../../tasks/ca_server.yml"

- name: Run OpenVPN server
  hosts: openvpn_servers
  vars_files:
    - "{{ playbook_dir }}/../../defaults/main/ca.yml"
    - "{{ playbook_dir }}/../../defaults/main/openvpn.yml"
    - "{{ playbook_dir }}/../../vars/main/ca.yml"
    - "{{ playbook_dir }}/../../vars/main/openvpn.yml"
  become: true
  tasks:
    - import_tasks: "{{ playbook_dir }}/provision.yml"
    - import_tasks: "{{ playbook_dir }}/../../tasks/openvpn_server.yml"