---
- name: Configure CA server
  hosts: ca-server
  become: true
  gather_facts: false
  vars_files:
    - ../../defaults/ca.yml
    - ../../vars/ca.yml
  tasks:
    - import_tasks: ./provision.yml
    - import_tasks: ../../tasks/ca_server.yml

- name: Run OpenVPN server
  hosts: openvpn_servers
  vars_files:
    - ../../defaults/ca.yml
    - ../../defaults/openvpn.yml
    - ../../vars/ca.yml
    - ../../vars/openvpn.yml
  become: true
  tasks:
    - import_tasks: ./provision.yml
    - import_tasks: ../../tasks/openvpn_server.yml