- name: Install packages
  package:
    name:
      - apt-utils
      - gcc
      - git
      - python3
      - python3-dev
      - python3-pip
      - libssl-dev
      - sudo
    state: present
    update_cache: yes
  become: true