---
- name: Converge
  hosts: ca-server
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../defaults/main/ca.yml"
    - "{{ playbook_dir }}/../../vars/main/ca.yml"
  tasks:
    - import_tasks: "{{ playbook_dir }}/../../tasks/ca_server.yml"