---
- name: Configure CA server
  hosts: ca-server
  become: true
  gather_facts: false
  vars_files:
    - ../../defaults/ca.yml
    - ../../vars/ca.yml
  tasks:
    - import_tasks: ../../tasks/ca_server.yml

- name: Generate client files
  hosts: client-host
  vars_files:
    - ../../defaults/ca.yml
    - ../../vars/ca.yml
    - ../../defaults/client.yml
    - ../../vars/client.yml
  become: true
  tasks:
    - import_tasks: ../../tasks/create_client_files.yml