---
- name: Configure CA server
  hosts: ca-server
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../defaults/main/ca.yml"
    - "{{ playbook_dir }}/../../vars/main/ca.yml"
  tasks:
    - import_tasks: "{{ playbook_dir }}/../../tasks/ca_server.yml"

- name: Generate client files
  hosts: client-host
  vars_files:
    - "{{ playbook_dir }}/../../defaults/main/ca.yml"
    - "{{ playbook_dir }}/../../vars/main/ca.yml"
    - "{{ playbook_dir }}/../../defaults/main/client.yml"
    - "{{ playbook_dir }}/../../vars/main/client.yml"
  become: true
  tasks:
    - import_tasks: "{{ playbook_dir }}/../../tasks/create_client_files.yml"